# Generated by Django 4.0 on 2022-01-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_type_name', models.CharField(max_length=50)),
                ('hostel_type_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'HostelType',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=5)),
                ('bed_spaces', models.CharField(max_length=5)),
                ('hostel_located', models.CharField(max_length=20)),
                ('is_full', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=10)),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Session',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=50)),
                ('hall_master', models.CharField(max_length=30)),
                ('chief_porter', models.CharField(max_length=30)),
                ('hostel_code', models.CharField(max_length=20)),
                ('hostel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.hosteltype')),
            ],
            options={
                'verbose_name_plural': 'Hostel',
            },
        ),
    ]
