# Generated by Django 4.0 on 2022-02-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_non_academicstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=200)),
                ('hostel_type', models.CharField(max_length=200)),
                ('hostel_code', models.CharField(max_length=50)),
                ('hall_master', models.CharField(max_length=200)),
                ('chief_porter', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Hostel',
            },
        ),
        migrations.CreateModel(
            name='Hostel_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_type_name', models.CharField(max_length=100)),
                ('type_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('bed_spaces', models.IntegerField()),
                ('max_occupancy', models.IntegerField()),
                ('isFull', models.BooleanField(default=False)),
                ('hostel_located', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.hostel')),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('session_start', models.DateField()),
                ('session_end', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Session',
            },
        ),
        migrations.CreateModel(
            name='Room_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.hostel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'verbose_name_plural': 'Allocation',
            },
        ),
    ]
