# Generated by Django 3.2.9 on 2022-02-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_student_level'),
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='student',
        ),
        migrations.AddField(
            model_name='room',
            name='student',
            field=models.ManyToManyField(to='account.Student'),
        ),
    ]
