# Generated by Django 3.2.9 on 2021-12-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allocation',
            new_name='Room_Allocation',
        ),
    ]
