# Generated by Django 3.2.9 on 2021-12-22 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_auto_20211222_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.hostel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.student')),
            ],
            options={
                'verbose_name_plural': 'Allocation',
            },
        ),
        migrations.DeleteModel(
            name='Room_Allocations',
        ),
    ]
