# Generated by Django 3.2.9 on 2021-12-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0006_auto_20211222_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_allocation',
            name='name',
        ),
    ]
