# Generated by Django 3.2.9 on 2022-01-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0007_remove_room_allocation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_type_name', models.CharField(max_length=100)),
                ('type_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('payment_status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
