# Generated by Django 3.2.9 on 2022-01-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0008_auto_20220101_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
