# Generated by Django 4.0 on 2022-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='other_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
