# Generated by Django 4.0 on 2022-02-17 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_academicstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_AcademicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(choices=[('csc', 'Computer Science'), ('bch', 'BioChemistry'), ('mcb', 'MicroBiology')], max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
