# Generated by Django 4.0 on 2022-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_non_academicstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mat_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
